backend = "fastresize"
color_space = "lch"
palette = "dark16"
check_contrast = true

[templates]
waybar.template = "waybar.css"
waybar.target = "~/.alatar/alatar_dots/sway/waybar/colors.css"
rofi.template = "rofi.rasi"
rofi.target = "~/.alatar/alatar_dots/rofi/wallust.rasi"
kde_colors.template = "kde.colors"
kde_colors.target = "~/.local/share/color-schemes/Wallust.colors"
qt6ct.template = "qt6ct.conf"
qt6ct.target = "~/.config/qt6ct/colors/wallust.conf"
qt6ct_main.template = "qt6ct-main.conf"
qt6ct_main.target = "~/.config/qt6ct/qt6ct.conf"
help.template = "help.tcl"
help.target = "~/.config/wallust/help.tcl"
emacs.template = "emacs-theme.el"
emacs.target = "~/.emacs.d/wallust-theme.el"
sway.template = "sway.conf"
sway.target = "~/.alatar/alatar_dots/sway/colors.conf"
zsh_prompt.template = "zsh-prompt.zsh"
zsh_prompt.target = "~/.config/wallust/zsh-prompt.zsh"
zellij.template = "zellij-theme.kdl"
zellij.target = "~/.alatar/alatar_dots/zellij/themes/wallust.kdl"
vscode.template = "vscode.json"
vscode.target = "~/.config/Code/User/settings.json"
vscode_oss.template = "vscode.json"
vscode_oss.target = "~/.config/Code - OSS/User/settings.json"
vscodium.template = "vscode.json"
vscodium.target = "~/.config/VSCodium/User/settings.json"
vscode_theme.template = "vscode-theme.json"
vscode_theme.target = "~/.vscode/extensions/wallust.wallust-theme/themes/wallust-color-theme.json"
vscode_theme_package.template = "vscode-theme-package.json"
vscode_theme_package.target = "~/.vscode/extensions/wallust.wallust-theme/package.json"
vscode_oss_theme.template = "vscode-theme.json"
vscode_oss_theme.target = "~/.vscode-oss/extensions/wallust.wallust-theme/themes/wallust-color-theme.json"
vscode_oss_theme_package.template = "vscode-theme-package.json"
vscode_oss_theme_package.target = "~/.vscode-oss/extensions/wallust.wallust-theme/package.json"
sddm_theme.template = "sddm-theme.conf"
sddm_theme.target = "~/.alatar/alatar_dots/sddm/alatar-theme/theme.conf"
